apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ihs3ojaoc-go
  janus-idp.io/tekton: ihs3ojaoc-go
  backstage.io/kubernetes-id: ihs3ojaoc-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ihs3ojaoc-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
