apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ihs3ojaoc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ihs3ojaoc-go 
  name: ihs3ojaoc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ihs3ojaoc-go 
